Add in gajira integration
ministryofjustice/laa-access-civil-legal-aid pull request #7
Opened 2024-05-28 10:25 UTC by TawneeOwl

## What does this pull request do?

Adds in jira ticket integration for the new access service

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [ ] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

2024-05-28 10:46 UTC, Pheonnexx approved these changes
LGTM

2024-05-29 10:56 UTC, BenMillar-CGI commented on .github/workflows/gajira.yml
> +name: Gajira
Would it be possible to name this something more descriptive? i.e. "Raise Jira Issue"

2024-05-29 11:02 UTC, BenMillar-CGI approved these changes
Looks good to me, thanks for this!

2024-05-29 11:03 UTC, BenMillar-CGI requested changes
I have left two comments around naming, feel free to adjust these or dismiss as you wish.

2024-05-29 12:17 UTC, BenMillar-CGI approved these changes
LGTM, thank you 👍

2024-05-29 12:19 UTC, merged