Feature/lga 3466 reason for contacting page
ministryofjustice/laa-access-civil-legal-aid pull request #82
Opened 2024-12-30 15:08 UTC by TawneeOwl

## What does this pull request do?

Required.

## Any other changes that would benefit highlighting?

Intentionally left blank.

## Checklist

- [ ] Provided JIRA ticket number in the title, e.g. "LGA-152: Sample title"

2025-01-06 15:27 UTC, BenMillar-MOJ approved these changes
LGTM, thanks for all your work on this!

2025-01-06 15:42 UTC, BenMillar-MOJ requested changes

2025-01-06 15:42 UTC, BenMillar-MOJ commented on app/contact/forms.py
> +    def api_payload(self):
Would you be able to write a unit test for this function please. Thank you very much!

2025-01-06 15:43 UTC, BenMillar-MOJ commented on app/contact/urls.py
> +            print("API Response:", result)
Would you be able to properly log this, or remove these

2025-01-06 16:46 UTC, BenMillar-MOJ approved these changes
LGTM, thanks for this! 👍

2025-01-07 09:37 UTC, said-moj commented on run_local.sh
> +git clone https://github.com/ministryofjustice/cla_backend ../cla_backend
Can this be moved to /tmp or perhaps create a tmp folder in the project which has it's content ignored in this repo

2025-01-07 09:39 UTC, said-moj commented on app/contact/api.py
> +        url=f"{hostname}/checker/api/v1/reasons_for_contacting/", json=payload
What do you think of storing the backend url plus `/checker/api/v1` in a config variable? perhaps something like backend_api_blah. As it will be common across all interactions with backend.

Also where do you authenticate with backend?

2025-01-07 11:04 UTC, BenMillar-MOJ requested changes

2025-01-07 11:04 UTC, BenMillar-MOJ commented on app/templates/contact/rfc.html
> +{% block pageTitle %}Legal aid is available for this type of problem - GOV.UK{% endblock %}
This page title is incorrect

2025-01-07 13:18 UTC, TawneeOwl commented on app/templates/contact/rfc.html
> +{% block pageTitle %}Legal aid is available for this type of problem - GOV.UK{% endblock %}
Good spot, updated

2025-01-07 16:01 UTC, merged